ENV_ADMIN_WXID = 'ADMIN_WXID'
ENV_HOST = 'HOST'
ENV_PORT = 'PORT'
ENV_PREFIX = 'PREFIX'
ENV_USERNAME = 'USERNAME'
ENV_TOKEN = 'TOKEN'
ENV_IMSDK_NAME = 'IMSDK_NAME'
ENV_COLLECT = 'WX_COLLECT'
ENV_API_GEWE = 'API_GEWE'

CONFIG_SEND_METHOD = 'fn_send_request'
CONFIG_URL = 'url'
CONFIG_TOKEN = 'token'
CONFIG_IMSDK_NAME = 'imsdk_name'
CONFIG_USERNAME = 'username'
CONFIG_HOST = 'host'
CONFIG_PORT = 'port'

CONFIG_APP_ID = 'app_id'
CONFIG_GEWE_TOKEN = 'gewe_token'
CONFIG_GEWE_API ='gewe_api'
CONFIG_TARGET_WECHAT_ID = 'target_wechat_id'

SESSION_DIR = 'session'
SESSION_LOGIN_FILE = 'session/login.jpg'
SESSION_CONFIG_FILE = 'session/config.json'

ERROR_CMD_FORMAT = '命令格式错误。'
ERROR_INIT = '服务初始化错误。'

TEMPLATE_URL = 'http://%s:%s%s/imsdk'

FLASK_APP_NAME = 'anywhere_door_imsdk_wxbot'
FLASK_STATIC_FOLDER = './'
FLASK_URL_IMSDK = '/imsdk'
FLASK_URL_LOGIN = '/login'
FLASK_URL_COLLECT = '/collect'
FLASK_HOST = '0.0.0.0'
FLASK_PORT = 80

PARAMS_TOKEN = 'token'
PARAMS_NAME = 'name'
PARAMS_TARGET = 'target'
PARAMS_DATA = 'data'
PARAMS_CODE = 'code'
PARAMS_MESSAGE = 'message'
PARAMS_USERNAME = 'username'

ERROR_CODE_SUCCESS = 0
ERROR_CODE_INVALID_TOKEN = -1
ERROR_CODE_INVALID_TARGET = -2

ERROR_MESSAGE_SUCCESS = 'success'
ERROR_MESSAGE_INVALID_TOKEN = 'token is invalid'
ERROR_MESSAGE_INVALID_TARGET = 'target is not this'

FROM = 'from'
WHITE_SPACE = ' '
NEWLINE = '\n'
COLON = ':'
