ENV_ADMIN_NICKNAME = 'ADMIN_NICKNAME'
ENV_HOST = 'HOST'
ENV_PORT = 'PORT'
ENV_PREFIX = 'PREFIX'
ENV_USERNAME = 'USERNAME'
ENV_TOKEN = 'TOKEN'
ENV_IMSDK_NAME = 'IMSDK_NAME'

DEFAULT_ADMIN_NICKNAME = '猫眼螺'
DEFAULT_HOST = '192.168.25.7'
DEFAULT_PORT = '8081'
DEFAULT_PREFIX = ''
DEFAULT_USERNAME = 'maoyanluo'
DEFAULT_TOKEN = '1998'
DEFAULT_IMSDK_NAME = 'wxbot'

CONFIG_ADMIN_NICKNAME = 'admin_nickname'
CONFIG_SEND_METHOD = 'fn_send_request'
CONFIG_URL = 'url'
CONFIG_TOKEN = 'token'
CONFIG_IMSDK_NAME = 'imsdk_name'
CONFIG_USERNAME = 'username'
CONFIG_HOST = 'host'
CONFIG_PORT = 'port'

LOGIN_PIC_DIR = 'login.png'
LOGIN_STATUS_STORAGE_DIR = 'itchat.pkl'

ERROR_CMD_FORMAT = '命令格式错误。'
ERROR_INIT = '服务初始化错误。'

TEMPLATE_URL = 'http://%s:%s%s/imsdk'

FLASK_APP_NAME = 'anywhere_door_imsdk_wxbot'
FLASK_STATIC_FOLDER = './'
FLASK_URL_IMSDK = '/imsdk'
FLASK_URL_LOGIN = '/login'
FLASK_HOST = '0.0.0.0'
FLASK_PORT = 80

PARAMS_TOKEN = 'token'
PARAMS_NAME = 'name'
PARAMS_TARGET = 'target'
PARAMS_DATA = 'data'
PARAMS_CODE = 'code'
PARAMS_MESSAGE = 'message'
PARAMS_USERNAME = 'username'

ERROR_CODE_SUCCESS = 0
ERROR_CODE_INVALID_TOKEN = -1
ERROR_CODE_INVALID_TARGET = -2

ERROR_MESSAGE_SUCCESS = 'success'
ERROR_MESSAGE_INVALID_TOKEN = 'token is invalid'
ERROR_MESSAGE_INVALID_TARGET = 'target is not this'

NEWLINE = '\n'
