ENV_ADMIN_WXID = 'ADMIN_WXID'
ENV_HOST = 'HOST'
ENV_PORT = 'PORT'
ENV_PREFIX = 'PREFIX'
ENV_USERNAME = 'USERNAME'
ENV_TOKEN = 'TOKEN'
ENV_IMSDK_NAME = 'IMSDK_NAME'
ENV_COLLECT = 'WX_COLLECT'
ENV_API_GEWE = 'API_GEWE'
ENV_SELF_HOST = 'SELF_HOST'
ENV_SELF_PORT = 'SELF_PORT'
ENV_SELF_PREFIX = 'SELF_PREFIX'
ENV_APP_ID = 'ENV_APP_ID'

CONFIG_SEND_METHOD = 'fn_send_request'
CONFIG_URL = 'url'
CONFIG_TOKEN = 'token'
CONFIG_IMSDK_NAME = 'imsdk_name'
CONFIG_USERNAME = 'username'

CONFIG_GEWE_TOKEN = 'gewe_token'
CONFIG_TARGET_WECHAT_ID = 'target_wechat_id'

ERROR_CMD_FORMAT = '命令格式错误。'

TEMPLATE_URL = 'http://%s:%s%s/imsdk'
TEMPLATE_LOG_URL = 'http://%s:%s%s/imsdk/log'
TEMPLATE_REGISTER_URL = 'http://%s:%s%s/imsdk/register'

FLASK_APP_NAME = 'anywhere_door_imsdk_wxbot'
FLASK_URL_IMSDK = '/imsdk'
FLASK_URL_COLLECT = '/collect'
FLASK_HOST = '0.0.0.0'
FLASK_PORT = 80

PARAMS_TOKEN = 'token'
PARAMS_NAME = 'name'
PARAMS_TARGET = 'target'
PARAMS_DATA = 'data'
PARAMS_CODE = 'code'
PARAMS_MESSAGE = 'message'
PARAMS_USERNAME = 'username'
PARAMS_TIMESTAMP = 'timestamp'
PARAMS_LEVEL = 'level'
PARAMS_TAG = 'tag'
PARAMS_LOG = 'log'
PARAMS_LOG_CONTEXT = 'log_ctx'
PARAMS_HOST = 'host'
PARAMS_PORT = 'port'
PARAMS_PREFIX = 'prefix'

ERROR_CODE_SUCCESS = 0
ERROR_CODE_INVALID_TOKEN = -1
ERROR_CODE_INVALID_TARGET = -2

ERROR_MESSAGE_SUCCESS = 'success'
ERROR_MESSAGE_INVALID_TOKEN = 'token is invalid'
ERROR_MESSAGE_INVALID_TARGET = 'target is not this'

EMPTY_STR = ''
RET = 'ret'

GEWE_PARAMS_APP_ID = 'appId'
GEWE_CALLBACK_URL = 'callbackUrl'
GEWE_CONTACTS_INFO = 'contactsInfo'
GEWE_TO_WXID = 'toWxid'
GEWE_CONTENT = 'content'

HEADER_TOKEN = 'X-GEWE-TOKEN'
HEADER_CONTENT_TYPE = 'Content-Type'
APPLICATION_JSON = 'application/json'

FROM = 'from'
WHITE_SPACE = ' '
NEWLINE = '\n'
COLON = ':'

LOG_LEVEL_DEBUG = 1
LOG_LEVEL_INFO = 2
LOG_LEVEL_WARN = 3
LOG_LEVEL_ERROR = 4
